version: 2.1
orbs: 
  node: circleci/node@1.1.6
jobs:
  test-client:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd client && npm install
            - run: cd client && npm test
  eslint:
    executor:
      name: node/default
    steps:
      - checkout
      - run: sudo npm install -g eslint
      - run: npm install
      - run: npm run eslint
workflows:
  test-client:
    jobs:
      - test-client
  lint:
    jobs:
      - eslint
