version: 2.1
orbs: 
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  eslint:
    executor:
      name: node/default
    steps:
      - checkout
      - run: sudo npm install -g eslint
      - run: npm install
      - run: eslint '*.js?(x)' # Eslint all .js and .jsx
workflows:
  build-and-test:
    jobs:
      - build-and-test
  lint:
    jobs:
      - eslint
